library(survival)
set.seed(12345)

fit.lung <- survreg(Surv(time, status) ~ sex + ph.ecog, data = lung)

object <- fit.lung
n.rep  <-  30
newdata <- tibble::as_tibble(dplyr::select(lung, time, status, sex, ph.ecog)) %>% tidyr::drop_na()
censor.dur <- c(200, 1100)

n.resample <- c(10, 30)


test_that("make sure extraction works for both with or without resampling", {
  sim <- surv_param_sim(object, newdata, n.rep, censor.dur)
  sim.raw <- extract_sim(sim)

  sim.resample <- surv_param_sim_resample(object, newdata, n.rep, censor.dur, n.resample, strat.resample = "sex")
  sim.raw.resample <- extract_sim(sim.resample)

  expect_equal(dim(sim.raw), c(6810, 7))
  expect_equal(dim(sim.raw.resample), c(1200, 7))
})

test_that("extract_sim works and warns when original data has conflicting 'event' column", {
  # Add an 'event' column not used in the model
  colon2 <- dplyr::as_tibble(colon) %>%
    dplyr::mutate(rx = factor(rx, levels = c("Obs", "Lev+5FU")),
           event = 1 - status) # event is not used in the model

  fit.colon <- survreg(Surv(time, status) ~ rx, data = colon2, dist = "lognormal")

  sim <- surv_param_sim(object = fit.colon, newdata = colon2, censor.dur = c(1800, 3000), n.rep = 5)

  expect_warning(
    sim.raw <- extract_sim(sim),
    regexp = "named 'event' which conflict with simulation output."
  )

  # Check that the output has only one 'event' column and it is from the simulation
  expect_true("event" %in% names(sim.raw))
  expect_false(any(duplicated(names(sim.raw))))
  # The event column should be 0/1 as generated by the simulation
  expect_true(all(sim.raw$event %in% c(0, 1)))
})
